### ISSUE TITLE
Using the ID of members in the group query

### ISSUE THREAD

**Issue by tschm** [lobnek/pyaddepar#1]
Currently I have to perform a clumsy join with the entities table to get the IDs for members in a group. The ID of the member could be included in the rows returned by the groups query. thanks

**Comment by akhileshgupta** [comment]
Based on your feedback, Addepar is working on a change to the API to include Group ID and member ID in the export file. Will keep you posted as we get it ready to ship.

**Comment by tschm** [comment]
Done
